#define TIME_TO_REFRESH_TIME_DATA_SEC (5 * 60)      // 5 minutes
#define TIME_TO_REFRESH_WEATHER_DATA_SEC (30 * 60)  // 30 minutes

#define SHOW_TIME_DATA_SEC 5
#define SHOW_WEATHER_DATA_SEC 4

#define BACKLIGHT_PIN D8
#define CITY_NAME "Gdansk"
#define NTP_CONNECTION_TIMEOUT_MS 10000
