#define TIME_TO_REFRESH_DATA_SEC (20 * 60) // 20 minutes

#define SHOW_TIME_DATA_SEC 5
#define SHOW_WEATHER_DATA_SEC 4

#define BACKLIGHT_PIN D8
#define CITY_NAME "Gdansk"
#define NTP_CONNECTION_TIMEOUT_MS 10000
